# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

# используем режим обычного пользователя для сборки проекта.
#root: deprecated key sudo (The key `sudo` has no effect anymore.)
#sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -aza-maxim@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="28294a46-2281-42f7-a5a8-48897793a1f7"